# Generated by Django 5.2.8 on 2025-11-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QnaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='qna.qnacategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Q&A Category',
                'verbose_name_plural': 'Q&A Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=200, verbose_name='Question Title')),
                ('content', models.TextField(verbose_name='Question Content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status')),
                ('category', models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('payment', 'Payment'), ('course_content', 'Course Content'), ('certificate', 'Certificate'), ('account', 'Account')], default='general', max_length=30, verbose_name='Category')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public')),
                ('is_faq', models.BooleanField(default=False, verbose_name='Is FAQ')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='question_attachments/', verbose_name='Attachment')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='Related Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('content', models.TextField(verbose_name='Answer Content')),
                ('is_staff_answer', models.BooleanField(default=False, verbose_name='Is Staff Answer')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted Answer')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='answer_attachments/', verbose_name='Attachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qna.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-is_accepted', '-is_staff_answer', 'created_at'],
            },
        ),
    ]
