# Generated by Django 5.2.8 on 2025-11-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('notice_type', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('update', 'Update'), ('event', 'Event'), ('urgent', 'Urgent')], default='general', max_length=20, verbose_name='Notice Type')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Show on Main Page')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice_attachments/', verbose_name='Attachment')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Read At')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='notices.notice', verbose_name='Notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notice Read Status',
                'verbose_name_plural': 'Notice Read Statuses',
                'ordering': ['-read_at'],
                'unique_together': {('notice', 'user')},
            },
        ),
    ]
