# Generated by Django 5.2.8 on 2025-11-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
