# Generated by Django 5.2.8 on 2025-11-12 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnd_lms_simple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Board Name')),
                ('board_type', models.CharField(choices=[('notice', 'Notice'), ('free', 'Free Board'), ('qna', 'Q&A'), ('event', 'Event')], max_length=20, verbose_name='Board Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Board Management',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MND Learning Management System', max_length=100, verbose_name='Site Name')),
                ('site_description', models.TextField(blank=True, verbose_name='Site Description')),
                ('admin_email', models.EmailField(default='admin@example.com', max_length=254, verbose_name='Admin Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
                ('hero_title', models.CharField(default='MND Learning Management System', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(default='Professional Military Education and Training System', max_length=500, verbose_name='Hero Subtitle')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Hero Image')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='Allow Registration')),
                ('email_verification', models.BooleanField(default=False, verbose_name='Email Verification')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_notice', models.BooleanField(default=False, verbose_name='Notice')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Secret')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnd_lms_simple.board', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post Management',
                'ordering': ['-is_notice', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled Date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress(%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mnd_lms_simple.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollment Management',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
